[package]
name = "webgl-triangle"
version = "1.0.0"
authors = ["Karl Pothast <karlpothast@gmail.com>"]
license = "CC0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = "thin"
